### ISSUE TITLE
Release v2.0.10 files on GH contain wrong extension (ESGST instead of traktflix)

### ISSUE THREAD

**Issue by airdrummingfool** [tegon/traktflix#110]
I downloaded the Chrome and Firefox versions of v2.0.10 (from https://github.com/tegon/traktflix/releases/tag/v2.0.10), and both files seem to contain the wrong extension; instead of traktflix, they contain Enhanced SteamGifts & SteamTrades (a different extension developed by @rafael-gssa). The previous release appears to be correct.

Update: I was able to install the newest version (2.0.10) from the Chrome Web Store without issue.

**Comment by rafael-gssa** [comment]
Oops. 😄

Should be fixed now, thanks for bringing this to my attention.
