### ISSUE TITLE
No Login/History Tabs

### ISSUE THREAD

**Issue by knuthen** [tegon/traktflix#112]
Hi!
I am running Firefox 68.0.1 (64-bit) and Traktflix v2.0.10.
Sice a couple of days ( I don't know if the recent traktflix update broke it) I don't have the history and/or login tabs in the little widget. Hence I can't scrobble manually anymore and neither do I know if I'm logged in or not.
Any idea?

**Comment by woxie** [comment]
Same issue on Chrome's latest version 76.0.3809.87 (Official buildl) (64 bits) and Traktflix v2.0.10.

**Comment by rafael-gssa** [comment]
Nothing appears when you open the extension popup?

**Comment by knuthen** [comment]
The only tabs are „options“ and „about“

**Comment by rafael-gssa** [comment]
If those are the only tabs, then you must be logged out. I'll see if there's an issue with authentication tokens expiring.

In the meantime, a workaround could be to go to the options page and clear the storage, but you'll have to configure your options again.

**Comment by woxie** [comment]
Thank you for the workaround!

**Comment by knuthen** [comment]
Clearing the storage als worked for me. Was able to login and got all the tabs back!

**Comment by woxie** [comment]
Whilst the tabs did come back, I continue getting this pop-up error every time I watch a new episode or movie:

![screenshot_003345](https://user-images.githubusercontent.com/33608237/62734469-b7e36980-b9ee-11e9-8dcc-1e84b14b2510.png)

I assume this means the app isn't able to automatically scrobble new content.

**Comment by rafaelgssa** [comment]
@woxie Can you confirm if this is still happening in v2.1.0?

**Comment by woxie** [comment]
> @woxie Can you confirm if this is still happening in v2.1.0?

It's working perfectly fine now. :)

**Comment by engeld** [comment]
I have the same Issue on Firefox 69.0.1 running v2.1.0, there are no Login/History Tabs visible:

![image](https://user-images.githubusercontent.com/944746/65835162-2b18a600-e2e3-11e9-8f38-f5af7919beb6.png)

It used to work previously without any issues. Clearing the storage and restarting firefox worked for me as well.

**Comment by asjmcguire** [comment]
I have the same issue (I even cleared the storage and disabled, re-enabled.)
No history tab - if I load it manually:
chrome-extension://ehlckfimahifadnbecobagimllmbdmde/html/history-sync.html
it lists my Netflix history - but every item says "Not found on Trakt" including the stuff that I know I have previously already synced to Trakt. The Chrome console is full of errors messages saying that the Trakt CORS Policy is not letting the extension access the resource. eg:

`Access to fetch at 'https://api.trakt.tv/sync/history/episodes/871049' from origin 'chrome-extension://ehlckfimahifadnbecobagimllmbdmde' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by ferges123** [comment]
Same here (no history tab, "Not found on Trakt" on manual access history link and windows pop-up with error), but 'clear storage' in plugin option resolved the issue.

**Comment by asjmcguire** [comment]
Followup: I noticed that Chrome storage had nothing at all stored for the extension, so I removed the extension from Chrome and re-added it, this fixed the problem.

**Comment by ciaron88** [comment]
I am also having this issue. I use Firefox but for me it works on chrome, so I am using that as a work around. Also, I have the same as ferges123 if I enter the history address manually on Firefox. Tried to clear, reinstall etc...

**Comment by MrMamen** [comment]
Same issue on chrome. There is no login-button (or history button).

**Comment by rafaelgssa** [comment]
Thanks for the additional info, @MrMamen. The 401 code leads me to believe my hunch was right and it's  really tokens expiring. Will see if I can work on it this weekend.

**Comment by MrMamen** [comment]
I've been looking at this further. From the background script I get an stack trace like this:
`Failed to load resource: the server responded with a status of 401 ()`
at Request.js:47
`response = await fetchObj(options.url, fetchOptions);`

On the injected scipts (aka Netflix) I find this error:
`Uncaught (in promise) TypeError: Cannot read property 'contains' of undefined`
ar Rollbar.js:26
`(await browser.permissions.contains({ origins: [`*://api.rollbar.com/*`] }))`

To be honest, the code is obfuscated so the files and linenumbers are reversely looked up based on the code seen in the console. I find both a bit strange, so it might be the chrome spits out something that is not true. For example, the first  is within a try/catch-block. So I would expect it to either go into the catch, or go on and reach error on another line.

**Comment by alsahlooly07** [comment]
Tivf

**Comment by rafaelgssa** [comment]
This should be fixed in v2.1.1. Let me know if not.

**Comment by MrMamen** [comment]
Will you release 2.1.1 to Chrome store?

**Comment by rafaelgssa** [comment]
I released it in the same day as I did for Firefox, but it appears that Chrome still hasn't reviewed it. The "Pending Review" is yellow, I'm not sure what that means.
