### ISSUE TITLE
Doesn't log pause

### ISSUE THREAD

**Issue by JigAma** [tegon/traktflix#113]
If i pause on Netflix, the extension doesn't pause the scrobble so Trakt think i'm at 1h45min while in reality i'm at 0h45min

That is bad because if you stop watching something, Trakt will log where you stopped 

then you can watch the same thing on another device and Trakt will send the information to the device so it can start exactly where you left off

**Comment by rafaelgssa** [comment]
Should be fixed in v2.1.0.
