### ISSUE TITLE
[Help] History Not Being Found, Firefox

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [tegon/traktflix#114]
**Issue:**

Just installed the plugin, and connected to trakt and I go to netflix and it's not finding my Netflix watched history. I went manually to my profile settings and checked that stuff was in my Netflix history. There was a full list. Just seems like the plugin isn't detecting anything.

**Things I notice:**

Upon going to the History page on the Traktflix plugin, a popup at the bottom appears saying `[object Object]`

**Things I've tried:**

Clearing storage and cache in the plugin settings.
Logging out and logging back into Trakt.
Logging out of netflix and back in.
Clearing browser cache & cookies.
Checking for browser and extension updates.
Reinstalling Traktflix extension.

**Info:**

Firefox Quantum - 68.0.2 (64 Bit)
Traktflix Extension - 2.0.10
Windows 10

**Comment by Z3ROGRAV1TYx** [comment]
Still having this issue, I had tried installing Trakt-flix on Chromium, and this issue was not present and I was able to sync my Netflix history to Trakt no problem. So this is an issue related to the Firefox addon. Hope to see this looked into, thanks!

**Comment by rafaelgssa** [comment]
Sorry for the delay, will look into it today.

**Comment by sevenup679** [comment]
got an similar issue on the firefox add-on. Only i don't even see the history link anymore.

**Comment by rafaelgssa** [comment]
Should be fixed in v2.1.0.

**Comment by Z3ROGRAV1TYx** [comment]
> 
> Should be fixed in v2.1.0.

Hm, so I updated and it still seems to be having trouble finding the history. 
It states "Failed to retrieve your history :(. We will work on a solution soon.". I tried reinstalling the addon as well as logging in and back out. Doesn't seem to find the history.

>Upon going to the History page on the Traktflix plugin, a popup at the bottom appears saying [object Object]

In my original statement that was the issue, that seems to be gone. That popup just changed to the "Failed to retrieve your history :(. We will work on a solution soon."

Screenshot: https://b.catgirlsare.sexy/2Q_O.png

**Comment by rafaelgssa** [comment]
Do you use Firefox Containers? Third-party cookies block? Anything that could be preventing traktflix from making a request to your Netflix page to get your history?

**Comment by Z3ROGRAV1TYx** [comment]
> 
> 
> Third-party cookies block?

This was the issue. Wasn't aware that would break it. Thank you.

**Comment by rafaelgssa** [comment]
Yeah, I forgot to mention that earlier. I had to disable it for the history sync page as well for it to work here. Looks like it blocks the request that traktflix needs to make to https://www.netflix.com/ViewingActivity. I'm not sure if there's a way to make it work with it enabled.
