### ISSUE TITLE
Dates incorrect with Netflix Viewing Activity sync

### ISSUE THREAD

**Issue by adammw** [tegon/traktflix#13]
Dates are specified in local format, i.e. Australian accounts show with DD/MM/YYYY instead of MM/DD/YYYY, but the parser uses JS Date constructor to parse the date. This results in invalid dates like 2/01/2016 being interpreted as the 1st of February (in the future).

## screenshots
![screen shot 2016-01-02 at 2 47 13 pm](https://cloud.githubusercontent.com/assets/153219/12073130/d7410882-b15f-11e5-9401-02dd06bd69fd.png)
![screen shot 2016-01-02 at 2 47 48 pm](https://cloud.githubusercontent.com/assets/153219/12073131/d81144ca-b15f-11e5-8620-211fb534c6a4.png)

A potentially better solution would be to hit the JSON API directly at https://www.netflix.com/api/shakti/7ffaa772/viewingactivity?pg=0&authURL=<authURL parameter found in page>, where it includes the date as number of milliseconds since unix epoch (also meaning the time of the play is available) rather than having everything show as midnight.

**Comment by tegon** [comment]
I didn't know about this API endpoint, that could really help. 
But the trakt API will return an UTC formatted date, and I have to compare them to check if the activity was already synced. Still looking for a solution to dates in other formats.

**Comment by MrMamen** [comment]
I have the same problem with but with dateformat DD.MM.YYYY.
My best suggestion would be to use [moment.js](http://momentjs.com/) for parsing (and working with) dates. But I have no idea how to find the format/locale which is used i netflix.

**Comment by MrMamen** [comment]
@tegon I currently have a working prototype on this issue. I need to clean up some code, and test a bit more before it is ready for merging, but just thought you'd like to know.

**Comment by tegon** [comment]
@MrMamen Ok, thanks for that.

**Comment by tegon** [comment]
Fixed on v1.0.5.5.
