### ISSUE TITLE
Plungin to Opera?

### ISSUE THREAD

**Issue by FloydKulis** [tegon/traktflix#146]
Plungin to Opera?

**Comment by rafaelgssa** [comment]
Can't you install from the Chrome store?

**Comment by aileensven29** [comment]
hello ho can tell me i look my movies and serrie's in vlc but then i want that it show on trakt.tv and i try all here and still not working ....please can someone help me whit this thank you..??,

**Comment by rafaelgssa** [comment]
@aileensven29 This isn't for VLC. I think this should work for VLC: https://github.com/iamkroot/trakt-scrobbler

**Comment by aileensven29** [comment]
hi now i install all like it whas write on the site i do everything and
install and it still not working ???
i dont now anymore what to do you can not help me for make it ok for the
vlc please??

Op vr 1 mei 2020 om 11:06 schreef Rafael Gomes <notifications@github.com>:

**Comment by rafaelgssa** [comment]
@aileensven29 Please ask in that repository. I have nothing to do with the VLC plugin.

**Comment by aileensven29** [comment]
ok thanks.

Op vr 1 mei 2020 om 20:12 schreef Rafael Gomes <notifications@github.com>:
