### ISSUE TITLE
History sync adds second watched 

### ISSUE THREAD

**Issue by icehead14** [tegon/traktflix#15]
Ive noticed that with history sync on it will add a second play for each episode already watched.

**Comment by tegon** [comment]
Are your Netflix dates in USA format? If not, maybe this issue is duplicated with #13

**Comment by icehead14** [comment]
They are USA format. Its not that the dates are wrong. Its just adding a second play to my trakt watched list.
 Let me try to grab a screen shot real quick

**Comment by tegon** [comment]
Ok, I'll try to reproduce here too.

**Comment by tegon** [comment]
Couldn't reproduce here. Might have been fixed on v1.0.5.5, since the Sync history was changed a lot. Please reopen if it happens again.

**Comment by icehead14** [comment]
Will do. I think it had to do with Netflix marking episodes as watched as soon as you open i .  Thanks

**Comment by tegon** [comment]
Yep, Netflix adds the activity to your history as soon as you open, even if it hasn't finished. But the [new code](https://github.com/tegon/traktflix/blob/master/app/scripts/src/content/watched-history.js#L74) is checking for a days difference between the dates on Trakt an Netflix. Maybe this fixed that.
