### ISSUE TITLE
More verbose history syncing

### ISSUE THREAD

**Issue by MrMamen** [tegon/traktflix#16]
As seen in other bug reports, the history syncing has some issues from time to time, depending on various factors. It would be much easier to correct/clean up invalid data if the complete list of synced (or rejected) data was listed. Even better if the user might check which plays to accept, and which to reject in advance.

A few reasons why this would be useful:
- #15 Data are doubled
- #13 Incorrect date format in localized areas
- Netflix adds everything you start playing to the history. (even if you just watch 10 seconds.)
- The user may already have checked in or marked episodes as played but not necessary the same time as Netflix recorded it.

**Comment by tegon** [comment]
I agree that could be useful. Some users wanted that all of his activity was marked seen so that's why the option to sync automatically can be unchecked.

**Comment by tegon** [comment]
Added on `master`. I will update the tests and release a new version soon.
Screenshot of `master`:
![screenshot 2016-03-18 01 55 38](https://cloud.githubusercontent.com/assets/3727827/13868910/b368c476-ecac-11e5-90a7-c434f455142a.png)
