### ISSUE TITLE
Some episodes don't have a season causing the JS to bomb out

### ISSUE THREAD

**Issue by GarethBlain** [tegon/traktflix#17]
I have just got this addon and am getting an error as [Line 26 of "viewing-activity-parser.js"](https://github.com/tegon/traktflix/blob/master/app/scripts/src/content/viewing-activity-parser.js#L26) expects 3 elements in the array but some shows only have one season and don't return a season at all so the array only has one two elements the show's name and episodes name (see screenshot below).

In the example below you can see the Series [Delete](http://www.netflix.com/title/70294801) doesn't have a season (or is only got one and they call it "Delete" after the Show's name). I have also got this issue with the show [Ascension](http://www.netflix.com/title/80029820). I'm sure there are others.

This causes the whole "SYNC NOW" button to bomb out and it is left on the spinning progress icon and Trakt.tv never seems to get any titles. :(

![Chrome Error](https://cloud.githubusercontent.com/assets/5220736/12130751/fbb8db98-b404-11e5-92b0-36c1103c1081.png)

**Comment by tegon** [comment]
Thanks for the report. This kind of show will be much harder to track, because the trakt API doesn't provide a episode search for a specific show. Maybe a solution would be to get all the episodes from that show, and then map them to find by the title. I'll try something like that.

**Comment by tegon** [comment]
Fixed on v1.0.5.5.
