### ISSUE TITLE
Not detecting anything

### ISSUE THREAD

**Issue by alibix** [tegon/traktflix#21]
It says to login to trakt, I then click to log in, it loads for a bit and then nothing happens?

**Comment by tegon** [comment]
Unfortunately the Trakt API is returning some timeouts these days. I've reopened #10 for give a better feedback when that kind of error happens.

**Comment by tegon** [comment]
Just tested here and the login worked. Can you test again?

**Comment by alibix** [comment]
Yes, it is working now! Thanks

**Comment by tegon** [comment]
Ok, thanks.
