### ISSUE TITLE
traktflix not working with chrome 48.0.2564.82 beta-m (64-bit)

### ISSUE THREAD

**Issue by F-AlFaris** [tegon/traktflix#24]
Am not sure if it's related to how the new chrome shows all extensions to the right of the URL bar but it's no longer working for me.

**Comment by tegon** [comment]
I need more details on this. The icon doesn't show up?

**Comment by F-AlFaris** [comment]
actually it does but there is no way I could sign in to trakt

**Comment by tegon** [comment]
The trakt login screen appears to you? Did you see any erros on console? When you open Netflix, you'll see a request like this one:
![screen shot 2016-01-30 at 3 13 32 pm](https://cloud.githubusercontent.com/assets/3727827/12697193/1b7a5778-c764-11e5-8f30-4dc17738c398.png)
If this succeeds you are logged in.
