### ISSUE TITLE
Trakt.tv search seems pretty bad...

### ISSUE THREAD

**Issue by some-guy-23** [tegon/traktflix#28]
Much of my Netflix history doesn't seem to match up properly. For example -

https://trakt.tv/search?utf8=%E2%9C%93&query=scrubs

I would propose instead of taking first result, to search through and see if there is an exact title match first, and use that if so.

**Comment by GarethBlain** [comment]
I was about to post a very simalar bug.
All of my Reign viewings (https://trakt.tv/shows/reign) are throwing up "Reign" from 1999 instead (https://trakt.tv/shows/reign-1999) on Trakt with this plugin. When I search on Tratk.tv I do find that "Reign" is the 4th but Reign-1999 is 5th so I'm not sure why the plug-in is making the match. Maybe taking the earliest entries in trakt.tv? Is there no way to filter by the (closest) year it started. Both Netflix and Trakt.tv have this don't they?

**Comment by tegon** [comment]
Trakt had some issues with their search which as solved yesterday. Probably is better now.
Anyway, I had some issues like that before, and made some [quick fixes](ob/master/app/scripts/src/content/item.js#L5). The options that you guys suggested can be done, but what I want to do in the future is use the TMDb API for that. It can search by year and language, which would solve other issues.
