### ISSUE TITLE
Traktflix history and netflix history

### ISSUE THREAD

**Issue by Tuxity** [tegon/traktflix#32]
Hello,

both history aren't the same. I watch 2 episodes of Better call saul yesterday, they are in my netflix history, but not in traktflix history. I've tried to refresh, I've the last version 1.0.6.3

**Comment by tegon** [comment]
Just these two? When they don't appear in the extension, probably some error occurred when the search was performed on Trakt API.
Can you see if it is some error message on the console?

**Comment by Tuxity** [comment]
Just this :

```
GET https://api-v2launch.trakt.tv/shows/marvel-s-the-defenders-1969/seasons/1?extended=images 404 ()
api-v2launch.trakt.tv/shows/marvel-s-the-defenders-1969/seasons/1?extended=images:1 GET https://api-v2launch.trakt.tv/shows/marvel-s-the-defenders-1969/seasons/1?extended=images 404 ()
```

And the Netflix title is `Better Call Saul: Saison 2: "Le gâteau à la crème"` it's because netflix is in french ?

**Comment by Tuxity** [comment]
Confirmed, I change my netflix language to english and now it works :/

**Comment by tegon** [comment]
Yep, when I get your history from Netflix, it doesn't have the episode number in the title. So I have to loop through all the episodes and compare the name. That's why I say that english is the only supported language.
