### ISSUE TITLE
TraktFlix missing items in history due to title mismatch between Trakt and Netflix

### ISSUE THREAD

**Issue by burkasaurusrex** [tegon/traktflix#33]
So it looks as though the titles in Netflix have to match perfectly to Trakt in order for it to be shown in TraktFlix?

I noticed a couple of things missing:

Last Man Standing S03E15 - Netflix title: "Taser," Trakt title: "Tasers"
Last Man Standing S03E21 - Netflix title: "April Come She Will," Trakt title: "April, Come She Will"

I'm guessing this is due to the fact that the Netflix history doesn't have episode numbers? It would be helpful though to show approximate matches using a fuzzy search with some adjustable threshold. Or at the very least be able to manually enter Trakt IDs to unmatched items in TraktFlix in order to sync the datetime stamp of the viewing.

Great work by the way!!! Really love this plugin. The work on the history sync has been great!

**Comment by tegon** [comment]
You're right, it is because the Netflix history doesn't have the episode numbers. I don't think I can manage to include a fuzzy search right now, sorry.
Manually include the Trakt ID is a better option, I'll see what I can do about.

**Comment by burkasaurusrex** [comment]
That sounds great! I just poked around a bit more, and it looks like the website doesn't readily expose the Trakt ID - maybe having the user input the slug and then the season and episode number would be better?

**Comment by tegon** [comment]
Looks like you're right. Unfortunately I'm in a rush recently so I couldn't do this yet. But I'll do as soon as I can.

**Comment by MetalArend** [comment]
This also misses titles with a ' in the title, for some reason.

**Comment by MrMamen** [comment]
There is a very similar problem if Netflix-language is set to something other than English. Some of the episodes and movies have a translated name, and no match is found. Having the ability to manually set this is a workaround.

**Comment by tegon** [comment]
Published in version 1.0.7. I've removed the report link (only one user has used by now) and inserted an "Paste Trakt.tv url" link. Now you can paste the Trakt.tv url to the correct item and tem sync what you want.
![screen capture on 2016-04-20 at 22-59-56](https://cloud.githubusercontent.com/assets/3727827/14695785/da7e82bc-074b-11e6-97d1-47d6c94aa4c4.gif)

**Comment by burkasaurusrex** [comment]
Nice!! Works like a charm!

**Comment by MetalArend** [comment]
This issue is actually not closed yet: special characters still give problems. And even worse, they don't even show up in the list, so you simply can't sync them, not even with the "paste trakt url".

**Comment by MetalArend** [comment]
Some examples:
Sense8 1x04 What’s Going On?
Sense8 1x09 Death Doesn’t Let You Say Goodbye
Sense8 1x12 Can’t Leave Her
Master Of None 1x07 Ladies & Gentlemen

**Comment by tegon** [comment]
Just tested here, they did appear in the list:
![screenshot 2016-04-28 09 19 40](https://cloud.githubusercontent.com/assets/3727827/14885540/65e39910-0d22-11e6-86b1-51cb9e1e6fe4.png)
Maybe your extensions isn't in the last version?

About the issue, I found out that Netflix uses a right single quotation mark (ASCII Hex code 2019) and Trakt.tv uses an single quote (ASCII Hex code 27) in the title. That's why they're evaluated as different.

```js
netflix = "I Can’t Leave Her"
=> "I Can’t Leave Her"
trakt = "I Can't Leave Her"
=> "I Can't Leave Her"
netflix == trakt
=> false
escape(netflix)
=> "I%20Can%**u2019**t%20Leave%20Her"
escape(trakt)
=> "I%20Can%**27**t%20Leave%20Her"
```

For this case I can replace this mark like this:
```js
netflix.replace("’", "'")
=> "I Can't Leave Her"
netflix.replace("’", "'") == trakt
=> true
```
And it should work. But for the `&` I can't replace it for `and` since it can broke other items.

**Comment by burkasaurusrex** [comment]
I didn't have any problems syncing "Master Of None 1x07 Ladies & Gentlemen" as well.

@tegon, maybe it would make sense to strip all punctuation and whitespace out of the Trakt and Netflix titles before you compare them? Given that you've confined the match to just the season of the show, I don't think you'd have any titles in the same season that are only different by special characters and whitespace, and it should increase the matching hit rate.

If you wanted to solve for the `&`, you could replace it with `and` in both the Trakt and Netflix title and it should match in every situation, no?
