### ISSUE TITLE
Not syncing history 

### ISSUE THREAD

**Issue by Wouter0100** [tegon/traktflix#34]
When I've opened my Netflix history sync tab (of the extension), I see some episodes not synced, e.g:
![screenshot from 2016-04-08 20-50-20](https://cloud.githubusercontent.com/assets/864520/14394235/8653cd20-fdcb-11e5-911f-57c7f2577dca.png)

It would be logical if I pressed the red switch and it's being synced, but it doesn't seems to? Is there any way to sync the missing episodes through this screen? And does that switch do something? (instead of let you see if it's synced or not)

Thanks!

**Comment by tegon** [comment]
You have to hit the "Sync now" button in the end of the page. The ones in red will be sent to Trakt.

**Comment by Wouter0100** [comment]
Ah, I haven't seen that one coming. Hmm. Is there any way to disable them all?

**Comment by tegon** [comment]
Currently it isn't. Im closing the issue since your question was answered. If you want that feature (enable/disable all) please open another issue with that request. Thanks.
