### ISSUE TITLE
"Select all" button for history

### ISSUE THREAD

**Issue by dcoferraz** [tegon/traktflix#35]
When viewing history, it would be nice a "check all" button on top to select all episodes and sync them.
The sync could have a status bar instead of a infinite loading status icons.

Thanks! =)

**Comment by tegon** [comment]
I can do the "check all" button. About the progress bar, I agree that would be better, but I don't know how to do it, since multiple requests are made to Netflix and Trakt.tv APIs when loading the history. Any help is appreciated.

**Comment by luizcarvalho** [comment]
:+1:

**Comment by tegon** [comment]
Added this in the latest release (v1.0.7.4)
