### ISSUE TITLE
Error accesing "Netflix history sync"

### ISSUE THREAD

**Issue by plalloni** [tegon/traktflix#36]
When I click on the "history" link in the traktflix dropdown header the new tab opens the header appears and an animated loading icon appears, and stays there forever.

When I check the console I found this error:

    Failed to load resource: the server responded with a status of 404 (Not Found)

For the following URL:

    https://www.netflix.com/api/shakti/XXXXXXXX/viewingactivity?authURL=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=&pg=0

(I replaced the X for the actual values).

**Comment by Tuxity** [comment]
I've exactly the same

**Comment by tegon** [comment]
Same here, Netflix probably changed something in this endpoint. I'll take a look later.

**Comment by tegon** [comment]
Fixed in version 1.0.7.1. Thank you for the report!

**Comment by plalloni** [comment]
Great!

**Comment by plalloni** [comment]
Unfortunately... not working here.

Now I see two HTTP 404 on these URLs:

- https://api-v2launch.trakt.tv/shows/24/seasons/2?extended=images
- https://api-v2launch.trakt.tv/shows/show-off-show/seasons/1?extended=images

And after that this error is displayed on console:

```
history-sync.js:1 Uncaught TypeError: Cannot read property 'toLowerCase' of null
  r.findEpisodeByTitle @ history-sync.js:1
  (anonymous function) @ history-sync.js:1
  n.onload @ history-sync.js:1
```

**Comment by tegon** [comment]
That one didn't happen with my account. I've added some code to prevent this error, can you update to version 1.0.7.2 and test it again?

**Comment by plalloni** [comment]
I still got those 404s and the history never showed up in traktflix... so I removed all cookies for trakt.tv and for netlfix.com then tried again, and then it worked (still having those 404s).

Thanks.

**Comment by tegon** [comment]
But the rest of your history was synced, right? Those shows aren't being found on Trakt, which is another issue. You can manually past the correct url for them, that should work.
