### ISSUE TITLE
History sync not working

### ISSUE THREAD

**Issue by Bavixke** [tegon/traktflix#40]
It keeps showing loading screen.

Console errors: 
- history-sync.js:1 Uncaught TypeError: Cannot read property '1' of null
- https://api.rollbar.com/api/1/item/ Failed to load resource: the server responded with a status of 429 (Too Many Requests)

**Comment by kabaka** [comment]
Seeing this as well.

https://rollbar.com/docs/rate-limits/

Could use some kind of output for end users, aside from the obvious adjustments to the Rollbar account.

**Comment by tegon** [comment]
Netflix has changed their API. Just published a new version with a fix.
