### ISSUE TITLE
Only sync history from active netflix profile

### ISSUE THREAD

**Issue by mattgiltaji** [tegon/traktflix#42]
I share a netflix account with my family, and each person has a separate netflix profile on the same account. I go to my profile, but when I try to sync the history, the history for all profiles goes into trakt.tv.

Would it be possible to have only the current netflix profile's history be synced, so that i don't have to remove all the stuff that other profiles watch?

**Comment by tegon** [comment]
I use two profiles in my Netflix account and this works as expected.
If I go to Netflix and chose a profile, I can then open the History Sync and only the items of that profile show up.
Can you describe the steps to reproduce this, so I can figure out what's going on?

**Comment by mattgiltaji** [comment]
Checking Netflix's profile viewing history manually, traktflix is operating as expected and the problem is with the data on the Netflix side. 

Sorry for not investigating more thoroughly before opening this issue.
