### ISSUE TITLE
Manual history sync - next page 

### ISSUE THREAD

**Issue by Santeria227** [tegon/traktflix#43]
Is there any chance you will be modifying the app to pull all of the netflix history at once?  I try to go page by page but at most it seems to get about 5x pages into my history and then lags out.  

I have several years worth of history that I would like to sync if possible.

**Comment by tegon** [comment]
The only way I can get the history from Netflix is page by page. I thought this would work with any amount of pages, but to be honest I don't have a big history like yours to test it.
The idea of this extension is to sync the most recent items, usually the first page is one used by most users.
