### ISSUE TITLE
Position of the Sync Now button

### ISSUE THREAD

**Issue by griffmiester** [tegon/traktflix#45]
Because I like to keep my syncing up to date, it is a little annoying that I have to scroll all the way to the bottom of the page to click on the Sync Now button.
Would it be possible to move it, or duplicate it to the top of the page?

(love the extension, and I actually use it in Opera also, with the help of the "Download Chrome Extension")

**Comment by tegon** [comment]
Thank you for the feedback. My biggest concern about doing this is that some people might end up hitting the sync button without reviewing some items at the end, and end up adding some wrong things to their history. (I get a lot of complains about that, even though the button is at the end)
Although it seems like a good feature for people that always click on sync, I think it would cause more harm for most of the users. 
What do you think? We can discuss more, I'm open to suggestions.

**Comment by vtdeleond** [comment]
Maybe,  whether I click sync button, you can show a preview screen with
"what I will sync",  then hit Save/Done or Cancel or even uncheck it before
Save/Done

**Comment by tegon** [comment]
If I understood correctly, that wouldn't change much right? It will give more work to the user in the end also.
One idea that I have is to change the list size (today is 100 items per page, mostly because that's what Netflix returns) to a smaller number (like 20 or 10) you guys think It would be better?

**Comment by vtdeleond** [comment]
Hmm, could be (20)... but you'll have to handle every pagination with Netflix return.

Make the easier one

**Comment by tegon** [comment]
Will be complex, for sure. I'll see if I can just duplicate it on top easily then.

**Comment by griffmiester** [comment]
Alternate suggestion:
What if you added an Options page for the trakflix extension, so you can choose if you want the Sync button only at the bottom or at the top+bottom.
Maybe even add a warning message if they click the checkbox, that says something like:
"If you choose to include the Sync Button at the top of the page, I can't be held responsible for the unintentional duplication of syncing of watched shows to Trakt"

**Comment by tegon** [comment]
Currently, I don't have a backend and the local chrome storage for extensions is limited, so the only thing I store is the Trakt's API access token. What do you think if the button's div had a position fixed, to it's always was visible?

![screenshot 2017-02-22 13 26 54](https://cloud.githubusercontent.com/assets/3727827/23221050/b4b2a2e4-f902-11e6-96dd-b52a281f0573.png)

**Comment by griffmiester** [comment]
I like it, but it does then fail the "have you scrolled through and checked all that you are about to sync" issue.

**Comment by tegon** [comment]
Yeah, I know. I will probably add a confirm dialog with a warning message.

**Comment by vtdeleond** [comment]
I guess that is the best way

**Comment by tegon** [comment]
Implemented on version `1.0.7.9`
