### ISSUE TITLE
History Sync not working

### ISSUE THREAD

**Issue by Harath** [tegon/traktflix#46]
Trying to use the netflix history sync feature to get my netflix history into trakt, but it's just throwing errors and doing nothing... for this screenshot i only select 1 movie which had been automatically detected so i turned on 1 movie and clicked sync

http://i.imgur.com/MeaGeIn.png

**Comment by tegon** [comment]
Hi, thanks for your report. The first ones are 404 for items that couldn't be found on trakt, those shouldn't block the sync process. The last ones for `file_path` are from images that I try to get from Tmdb. Those shouldn't be happening and may be the reason that the sync is not working for you. I'll take a look at this.

**Comment by tegon** [comment]
I've handled the error on version `1.0.7.9`. Can you test again?

**Comment by vtdeleond** [comment]
It's working good

**Comment by Harath** [comment]
Sure I'll give it a shot and report back!

**Comment by Harath** [comment]
looks good! seems to be ok now

**Comment by tegon** [comment]
Great, thank you!
