### ISSUE TITLE
Netflix history sync freezing/taking forever...

### ISSUE THREAD

**Issue by whoischristopher** [tegon/traktflix#47]
Hi there,

I installed the plugin, logged into Netfliex, and completed the integration with Trakt.   i then click on History sync, and it showed the header, but just keep spinning away for minutes without any error or data...

What can I do to troubleshoot/resolve this?

Thank you.

Chris

**Comment by tegon** [comment]
Can you take a screenshot of the dev tools console and network tabs?

**Comment by thilux** [comment]
Same problem here... please find the request screenshots attached.
<img width="740" alt="screen shot 2017-03-10 at 15 30 27" src="https://cloud.githubusercontent.com/assets/4541251/23807961/95324b62-05a6-11e7-8ac0-e86dc01c3297.png">
<img width="738" alt="screen shot 2017-03-10 at 15 30 15" src="https://cloud.githubusercontent.com/assets/4541251/23807962/9534e7a0-05a6-11e7-8b75-0795f1314ff4.png">

**Comment by tegon** [comment]
Oh, I see. Netflix must have changed this URL again. Too bad they don't provide a public API, we have to go through this over and over again.
Anyway, thank you guys for the report. I'll dig in Netflix later and try to find the new URL.
Thanks

**Comment by whoischristopher** [comment]
I just confirm that my dev tool console/network tab looks just like what thilux posted - getting the error 404 on the history URL.

**Comment by tegon** [comment]
Fixed in version `1.0.8`. Can you guys test to see if it is working again?

**Comment by whoischristopher** [comment]
works for me now.  Thank you!

**Comment by thilux** [comment]
Working fine, now. Thank you!!!

**Comment by tegon** [comment]
Ok, thanks!
