### ISSUE TITLE
History sync not working 

### ISSUE THREAD

**Issue by milch** [tegon/traktflix#48]
Hi,

I just downloaded your extension and tried to sync my Netflix history, however, it doesn't seem to be working. When I launch history sync, the developer console log is full of these 504 errors:

<img width="874" alt="screenshot 2017-03-16 15 17 58" src="https://cloud.githubusercontent.com/assets/279407/24021007/f81c6730-0a5b-11e7-939c-085b86eacf22.png">

**Comment by tegon** [comment]
Thanks for your report.
504 is a request timeout from Trakt's API. They might be having some issues now, it should be fixed soon.
I tested here and some requests finished, other didn't. Unfortunately, the history sync isn't handling errors correctly - I plan to fix that soon - so the page simply doesn't render anything.

**Comment by tegon** [comment]
Just tested here and seems to be stable now. Can you confirm that is working for you now?

**Comment by milch** [comment]
@tegon Sorry for the delay, I was on vacation. I can confirm that it is working now, thank you! 👍
