### ISSUE TITLE
Feature Request: Mine Viewing Activity

### ISSUE THREAD

**Issue by marsman12019** [tegon/traktflix#5]
It's fairly easy for a user to access their [Viewing Activity](https://www.netflix.com/WiViewingActivity), which includes comprehensive information regarding which shows/movies/episodes have been watched, and the date on which they were watched. The data on the page is structured very well, and using something like [Kimono](https://www.kimonolabs.com/) or a homespun extractor would collect that data perfectly. From there, adding those shows to Trakt would be fairly easy. It could even be extended to ratings as well.

**Comment by tekanoma** [comment]
I think this should be something you have to activate manually when on the viewing activity list unless it does not cause duplicates on trakt when it syncs the list

**Comment by tegon** [comment]
I'm already [working](https://github.com/tegon/traktflix/tree/viewing-activity) on that. I'll planning to compare the dates with Trakt history to not cause duplicates.

**Comment by tekanoma** [comment]
I still think it should be optional because I've had others accidentally use my Netflix profile so it would add things I never watched myself and with a lot of what I've watched I manually added them on trakt but sometimes not on the day I watched, so for me it could add duplicates and things I never actually saw myself but it does seem like a feature a lot of people want so maybe have it on by default but with a warning and option to turn it off, or does it require going to the viewing activity page to sync the previously watched movies and shows?

**Comment by tegon** [comment]
I agree to left an option to turn it on/off..

**Comment by Wouter0100** [comment]
Hmm.. On this way I don't need to add them manually when watching through a mobile app or such, right? When I start the Chrome, it could sync Netflix and Trakt.tv. This would be an awesome feature indeed. I will try to contribute in the near future for this functionality.

**Comment by tegon** [comment]
It will run when you open Netflix, that's when the extension's content script is run.
I'm lacking of time lately, but I'll try to finish it soon

**Comment by intel352** [comment]
Excited for this, would be a killer feature. Kimono didn't prove to be stable enough for me in the past (tried it several times, but ~6 months ago), would much prefer a dedicated plugin such as this.

**Comment by tegon** [comment]
I almost finished this yesterday, writing unit tests now.
I want to release this in beta first, to catch some bugs before release it to chrome store. 
Any of you guys are willing to help test it?

**Comment by Wouter0100** [comment]
Yeah, of course! The viewing-activity branch?

**Comment by tegon** [comment]
Yup, but I need to finish some details before, I will say here when finished ok?

**Comment by Wouter0100** [comment]
Okay.

**Comment by tegon** [comment]
Ok guys, this is finally ready to test. Anyone who can help, please go to the `viewing-activity` branch and see if any bugs are found.
This is a big feature and would be nice to test it before releasing to the store.
Thanks.

**Comment by tegon** [comment]
Released in beta, anyone who finds a issue, please report so we can make sure is working correctly.
