### ISSUE TITLE
Use thetvdb as fallback for series

### ISSUE THREAD

**Issue by MrMamen** [tegon/traktflix#52]
themoviedb is great because it supports series and have images in higher resolution, but thetvdb seems to have a much larger database. I suggest using it as a fallback, or perhaps even as the first choice since there is no use for a high resolution image anyway.

**Comment by tegon** [comment]
Are some shows images missing from TMDB?
I choose to use it mainly because it supports both movies and shows. I didn't want to add another dependency on the project.

**Comment by MrMamen** [comment]
Good point! No point in fixing a problem that is not there. I don't know any examples as of now, but as Netflix is constant changing, and that there are a lot of regional differences I am sure that there is possible to find something.
