### ISSUE TITLE
[Suggestion] The ability to add movie to Trakt.tv watchlist

### ISSUE THREAD

**Issue by nasapunk88** [tegon/traktflix#53]
Would it be possible to add a button on the Netflix page, or by clicking the extension, to add the movie to your Trakt.tv watchlist? Otherwise, if it cant find a match, open a new tab to manually search for it. 

I have bookmark folders with 100s of Netflix movies I want to watch and would love an easy way to instead directly add to a Trakt.tv watchlist for easy organizing.

**Comment by tegon** [comment]
Hi, thanks for your suggestion. Just to try to understand, which would be the advantages of this compared to the Netflix's watchlist?

**Comment by nasapunk88** [comment]
The problem is that I use a shared account so I cannot use Netflix's watch list without messing up other peoples . I've been searching for an easy way to manage my own integrated watch list independent of Netflix.

**Comment by tegon** [comment]
But you can use the same account with different profiles - and therefore different lists, right?

**Comment by nasapunk88** [comment]
You can only have up to 5 profiles which doesn't cover my family size.

**Comment by tegon** [comment]
Ok, got it. I believe you have a very specific use case. It seems better to have this feature as a standalone plugin - maybe a simple JS script will do, and you can use it as a bookmarklet.
