### ISSUE TITLE
Stops tracking when netflix to streamed to chromecast

### ISSUE THREAD

**Issue by dylanswilliams16** [tegon/traktflix#54]
When you stream netflix from Chrome to a Chromecast (on netflix.com) the plugin stops recognising that you are watching a show and also stops scrobbling.

**Comment by tegon** [comment]
Hi, this is a known issue. Unfortunately, Netflix changed their player on Chromecast, and it doesn't include enough information about the movie/episode, so I can't track it anymore 😞
