### ISSUE TITLE
Unable to load history

### ISSUE THREAD

**Issue by Mr-Lambert** [tegon/traktflix#55]
I am unable to load my viewing history in traktflix. The history sync feature has been working fine up until a few days ago. Now, the history sync page fails to load any watched items.

To reproduce:
1 Log into traktflix
2 Click the 'History' tab in the chrome widget
3 Observe the history sync page - loading indicator moves continuously and the page fails to load

The console is filled multiple instances of the following error data for different watched items:

OPTIONS https://api.trakt.tv/sync/history/episodes/40970 504 ()
r._send @ history-sync.js:1
(anonymous) @ history-sync.js:1
safeCallbackApply @ VM412 extensions::sendRequest:21
handleResponse @ VM412 extensions::sendRequest:74
history-sync.html:1 XMLHttpRequest cannot load https://api.trakt.tv/sync/history/episodes/40970. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://bmoemkaigjgcgjjnpmdgkifndiidkeji' is therefore not allowed access. The response had HTTP status code 504.

I have tried reinstalling the extension and clearing web data/cache, but the problem persists.

**Comment by chrisofspades** [comment]
I m having the same issue with loading the history. I think trakt's api is down. I got the same 504 response when I tried a test from here: http://docs.trakt.apiary.io

**Comment by tegon** [comment]
Yep, many times they have a big load and start to return a timeout (504).
The main problem here is that the extension is not treating these errors correctly, so it seems like it is a problem in the extension itself.
I plan to fix this soon. Thanks for your report.
