### ISSUE TITLE
Sync errors; also multiple plays?

### ISSUE THREAD

**Issue by jcrben** [tegon/traktflix#56]
Notice a couple issues. Note that I'm canceling my Netflix account so this really isn't a big deal for me - feel free to close it. I'm reporting it as an fyi. I'll also drop a link to this into the VIP forum thread at https://trakt.tv/forums/general/topics/trigger-a-resync-with-netflix?page=1. 

1. The first one, when I log in and try to access Netflix:
![image](https://user-images.githubusercontent.com/5614134/27256587-a7e830ee-536e-11e7-9e63-8d6c78cee363.png)

I'm pretty sure I successfully logged in initially...

2. I noticed that some things that I all the way through show multiple plays - often 3. Wondering if it might be due to stopping and starting, but all episodes in an entire series sometimes have 3. Is or was this a known issue? If I leave and pick up something later, is a new play recorded? Because I'd rather not record a play for every click... perhaps a note could be put on the readme about this type of issue.

**Comment by tegon** [comment]
Hello, thanks for your report!
First of all, this extension is independent of Trakt.tv, so I think that the thread at the VIP forum is not the place to report any errors, it's better to do it here where I can reply.

1 - This was a problem on Trakt.tv's API, suddenly it started to reply with **502** for the `/users/me` endpoint - which I rely on to see if the user is logged in. It is working again now.

2 - I don't rely on clicks. The extension uses an interval and checks the current URL. If it contains a `watch` in it, it tries to start a scrobble on Trakt. See [watch-events.js](https://github.com/tegon/traktflix/blob/master/app/scripts/src/content/watch-events.js).
This seems really odd. All the plays are recorded at the same time on Trakt?

**Comment by jcrben** [comment]
I didn't report it there originally, but I left a link to this in a thread about this tool. For #1, isn't that the type of thing that should be reported to Justin at trakt.tv? Need to figure out why it failed. 

For #2, yeah. It wasn't too many so I cleaned them up manually. I was going to reproduce it but then I ran into #1. Maybe I'll try again sometime, but I'm moving away from Netflix anyhow...

**Comment by tegon** [comment]
Yep, I've already reported it.
Well, I've just watched Designated Survivor's Season 1 and I didn't have any duplicated plays. If that happens again for you, or anyone else, please leave a comment and I'll look into it.
Thanks again.
