### ISSUE TITLE
[Rollbar]: TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by MrMamen** [tegon/traktflix#57]
Every time I build use uglify (building for production), the script is obfuscated and doesn't work with rollbar. (I've experienced no other problems.)

The stacktrace is:
content.js:2 [Rollbar]: TypeError: Cannot read property 'call' of undefined
    at a.t (content.js:1)
    at a.configure (content.js:1)
    at Object.c.init (content.js:1)
    at Object.n.traktflix\app\scripts\src\rollbar.js../settings (content.js:1)
    at o (content.js:1)
    at content.js:1
    at Object.n.traktflix\app\scripts\src\content\content-controller.js.../chrome-storage.js (content.js:1)
    at o (content.js:1)
    at content.js:1
    at Object.n.traktflix\app\scripts\src\content\content.js.../rollbar.js (content.js:1)

Not sure if it is related, but I've noticed that much of the packages are outdated and very old. Even the node version is ancient.

**Comment by tegon** [comment]
Did you change `rollbarToken` to a valid one in `config.json`?

**Comment by MrMamen** [comment]
Yes it is uglify. If I remove the line from gulpfile.js, everything works. My best guess is that it is some transitive dependency that has been updated and thus not working.

**Comment by tegon** [comment]
It may be something like this. Did you run `npm install` recently? It has been some time since I have run this, but I'll try again this weekend to see if I get the same error.

**Comment by MrMamen** [comment]
yes, I tried it on two separate machines, both "clean". I'm guessing that if you delete (or backup) node_modules you will experience the same thing.
