### ISSUE TITLE
Issue when manually adding item from trakt

### ISSUE THREAD

**Issue by MrMamen** [tegon/traktflix#59]
In history sync, there seems to be a problem when entering a manually trakt-URL. The button is defaulted to off (or at least seems to be), but clicking the switch triggers an animation for "close". After one more click the button is on, as expected.

**Comment by tegon** [comment]
I don't understand exactly what the problem is, can you attach a gif or something like that to help?

**Comment by MrMamen** [comment]
Steps to reproduce:
1) Find and item where netflix title and trakt title doesn't match. Stranger Things usually don't match, but setting netflix language to something other than english also helps.
2) Manually add the trakt url
3) Observe that scrobble-switch is set to off
4) Press switch
5) Observe that the scrobble-switch is still set to off
6) Press switch again
7) Observe that the switch if finally set to on

**Comment by tegon** [comment]
Oh, I see it. In fact, this UI is far from perfect. I'll see what I can do.

**Comment by gsrafael01** [comment]
Can you confirm if this is still an issue in v2.0.8? I think I fixed this, but I don't remember.

**Comment by MrMamen** [comment]
Seems fixed now.
