### ISSUE TITLE
Episodes not being scrobbled when stopped on next episode countdown

### ISSUE THREAD

**Issue by krikmo** [tegon/traktflix#6]
When I binge watch, it always works, but watching one episode almost never registers. Am I doing something wrong?

**Comment by tegon** [comment]
Have you tested this with more than one show? 
This looks like #2, could you see if the `/stop` on Trakt API is being called, and the progress of it?

**Comment by krikmo** [comment]
That's odd. Tried three times now (with different shows) and it worked. 

The stop was called:
```javascript
{"action":"scrobble","progress":95.75,"sharing":{"facebook":false,"twitter":false,"tumblr":false},"episode":{"season":3,"number":6,"title":"The Ocean Walker","ids":{"trakt":339997,"tvdb":306158,"imdb":null,"tmdb":null,"tvrage":304665}},"show":{"title":"Arrested Development","year":2003,"ids":{"trakt":4565,"slug":"arrested-development","tvdb":72173,"imdb":"tt0367279","tmdb":4589,"tvrage":2649}}}
```
Well, thanks anyway. Sorry for the false alarm and congrats on this awesome extension.

**Comment by tegon** [comment]
No problem! If you find any issues, let me know. Thanks.
