### ISSUE TITLE
How long should history sync take??

### ISSUE THREAD

**Issue by Slicerking2000** [tegon/traktflix#64]
I have had this running for 2 hours and nothing has happened I just have a spinning red circle.  How do I tell if its an error like the servers are down or if its just taking this long to pull data?

**Comment by vishal8492** [comment]
For me similar thing is happening, it did seem like trakt API was giving up when pulling historical data.

**Comment by tegon** [comment]
Something definitely went wrong. Can you add a print screen of the console?
The errors can help me find the problem. Please add it in #63, I'll close this one since its a duplicate.
Thanks.
