### ISSUE TITLE
TV show Dynasty

### ISSUE THREAD

**Issue by Karoollis** [tegon/traktflix#66]
Hi,
while watching Netflix new show Dynasty, trackflix records it as the old show [Dynasty 1981](https://trakt.tv/shows/dynasty), not the new one [Dynasty 2017](https://trakt.tv/shows/dynasty-2017). Maybe there is a way to fix it.
Thanks.
P.S. amazing application <3

**Comment by tegon** [comment]
Hello, thanks for your report.
How does the title appear on the Netflix player? Is it just `Dynasty`?

**Comment by Karoollis** [comment]
Yeah

**Comment by tegon** [comment]
I see. I've fixed some of these before by [wrapping the title inside double quotes](https://github.com/tegon/traktflix/blob/master/app/scripts/src/content/item.js#L12).
But it seems like it won't work with this one. When something like this happens, you can test in the Trakt site's search itself. The first show returned is the one we'll use in traktflix.

https://trakt.tv/search?query=%22Dynasty%22&type=show

https://trakt.tv/search?query=Dynasty&type=show

I'm not sure how to fix this, I'll take a deeper look in the weekend.

**Comment by tegon** [comment]
I've updated to version `1.0.8.3` with a possible fix. Can you update and test it now?
