### ISSUE TITLE
The AddOn Doesn't Scrobble to Trakt

### ISSUE THREAD

**Issue by JayteeMedia** [tegon/traktflix#69]
When I use this I always it doesn't scrobble to trakt account. I have to actually sync for it to update my trakt account. I am using Chrome on MAC. Not sure why??

**Comment by tegon** [comment]
Hi, which show/movie are you watching? How the title appears on the Netflix player?

**Comment by JayteeMedia** [comment]
https://www.netflix.com/watch/80117697?trackId=13462260&tctx=0%2C0%2C40312074-a519-48e4-ae12-401ebad01790-231537417

**Comment by JayteeMedia** [comment]
?????

**Comment by tegon** [comment]
Sorry, I didn't have much time to work on this lately.
I tried here with The Punisher and it worked correctly. It's important that Trakt.tv only marks an episode as watched if the progress is 80% or more.
You also have to click on back to browse or change to another episode, if you just close the browser tab after you finish to watch the episode won't be tracked.
