### ISSUE TITLE
Chrome extension not staying logged in. Each time the browser is restarted it needs to log in again

### ISSUE THREAD

**Issue by muhammedchand** [tegon/traktflix#74]
This stop syncing history and at sometimes it appears to log in but looking at the console output of my browser the error is coming from the history being requested for an account that isn't logged in to.  Currently there is not pop up request for log in so I can't even log in witout restarting the browser

**Comment by Hillgrove** [comment]
I can second this.. I have a hard time finding a tracking service that actually works. Trakt has it's pros and cons, Simkl has it's pros and cons.. just sad that one doesn't stand out and "just works"...

**Comment by rafaelgssa** [comment]
Closing this as it should no longer be a problem, let me know otherwise.
