### ISSUE TITLE
Save trakt URL links in a database

### ISSUE THREAD

**Issue by Gonzom** [tegon/traktflix#76]
I've been using the "update item" option to add missing trakt URL links for items in my list, but I was wondering if there is a plan to use this data to fetch this data for future users.

What I mean is that after a set amount of users add a missing trakt URL for an item, the system will know to offer this link for any other user so they won't need to use this process again. You could set the color/an icon to make it visible different from other items. This would make this process much more user-friendly.

As a side note, even for myself these links do not save, which means if for any reason I'd like to sync an item again, I need to repeat this whole process.

**Comment by gsrafael01** [comment]
This was added to v2.0.0.
