### ISSUE TITLE
jshint seems to be unused

### ISSUE THREAD

**Issue by MrMamen** [tegon/traktflix#78]
Either the codebase should get an overhaul, or the jshint file should be removed all togheter. No linting or such seems to be applies as of now. For example useStrict and unused variables are seen a lot of places.
https://github.com/tegon/traktflix/blob/7d6b4d342e0fe26c15621e0f6bcb421da51fe010/.jshintrc

**Comment by gsrafael01** [comment]
Switched to eslint.
