### ISSUE TITLE
Feature request: Chromecast support

### ISSUE THREAD

**Issue by freijon** [tegon/traktflix#8]
Chromecasts only work partially at the moment. When starting an episode with the normal player and then switching to Chromecast mode, it continues scrobbling (the icon is red). However, when switching episodes (while still in Chromecast mode) it behaves like you stop the episode.

**Comment by tegon** [comment]
Unfortunately, I won't be able to hack into this, since I don't have a chromecast. But I will be happy to accept a PR.

**Comment by freijon** [comment]
Let me know how I can support you on this and I'll be happy to do so

**Comment by freijon** [comment]
I'll take a look at the code and try to figure out how it works. JS is new for me.

**Comment by tegon** [comment]
Just borrowed a chromecast from a friend, can you explain better what is happening?

**Comment by freijon** [comment]
When I start watching, I usually start the episode with the web player and then when it's already running/scrobbling I start streaming to the chromecast. Scrobbling continues to work when finishing this episode. But when I switch episodes (stacked window symbol) when streaming to the chromecast, Traktflix doesn't detect that a new episode is playing. Sometimes when I click the Traktflix icon it shows the correct episode name but still doesn't scrobble. Haven't figured out yet what the behavior is exactly. Let me know if I can assist in any way.

**Comment by tegon** [comment]
Looks like I've found the issue. I'm checking for a url change with `location.pathname`. But when in the cast mode, Netflix only changes the url's hash. I'll came up with a solution soon.
