### ISSUE TITLE
UX: Error handling with timeouts or bad gateway is not represented with "Update Item"

### ISSUE THREAD

**Issue by Maelstromeous** [tegon/traktflix#81]
When you press "Update Item" to match a Trakt link to a Netflix episode, there's often the time that Cloudflare will chuck the request out for some reason. Looks like there's an API error at the Trakt level (rate limits maybe?)

Either way, the user isn't informed, and sees nothing. There's also no indication that the item is actually being updated, therefore bad UX.

![chrome_2018-07-14_14-31-14](https://user-images.githubusercontent.com/1776058/42724895-b43f7a44-8772-11e8-9e10-5ad32d52a7e3.png)

**Comment by gsrafael01** [comment]
This should no longer be an issue in v2.0.8.
