### ISSUE TITLE
"Next Page" is extremely underperformant

### ISSUE THREAD

**Issue by Maelstromeous** [tegon/traktflix#82]
Looking at the network tab, it's making a metric crapton of API calls, all the while the user is presented with a page that simply isn't loading.

Items should be loaded in, and in the background the pictures / matching to Trakt etc should be done asynchronously in order for the user to actually do something on the page.

Otherwise people are just not gonna load the next page in the future and will miss scrobbles if they've got a lot to catch up on.

**Comment by gsrafael01** [comment]
This should no longer be an issue in v2.0.8.
