### ISSUE TITLE
Currently not matching series and very slow!

### ISSUE THREAD

**Issue by Richigeht** [tegon/traktflix#84]
Hi
Seems like the plugin currently is not working correctly.  95% of the Common Netflix Series i watched are not matching up and the plugin is very slow to load if it even does load once successfully!

**Comment by MrMamen** [comment]
Is this still present? Are you using Netflix with English language?

**Comment by Richigeht** [comment]
Hello 
Seems to work again for most of the stuff. Using Netflix in English yes.  

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet
