### ISSUE TITLE
History Timestamp off by 1 hour

### ISSUE THREAD

**Issue by elbaso** [tegon/traktflix#85]
The History page is showing the Netflix timestamp as 1 hour earlier than the actual watched time for every item on the page. When I sync up with Trakt, the timestamps are 1 hour earlier there as well.

I'm in the UTC+3 timezone.

**Comment by elbaso** [comment]
Note that when I checked the Netflix Recent Streaming Activity Page, the timestamps there are shown correctly in the UTC+3 timezone and not off by 1 hour.

**Comment by MrMamen** [comment]
Netflix records when you start watching a show or a movie, not when it ends. Could this be the case? If you start a show at 11 and it ends 12, Netflix records this as watched on 11.

**Comment by elbaso** [comment]
No, it's not the start time that's being recorded.
The timestamp is always exactly 1 hour earlier, regardless of the length of the Netflix program (30 mins, 1 hour, 2 hours, etc).
I just wonder if it's a timezone issue.

**Comment by gsrafael01** [comment]
Hi, is this still an issue?

**Comment by elbaso** [comment]
> Hi, is this still an issue?

I'm not sure as I haven't been using the extension recently. I'll give it a try and come back.

**Comment by elbaso** [comment]
> Hi, is this still an issue?

Seems to be working fine now. No longer an issue for me.
