### ISSUE TITLE
Extension pulled from Chrome Web Store

### ISSUE THREAD

**Issue by tjorim** [tegon/traktflix#86]
Seems like this extension got pulled from the Chrome Web Store.
https://chrome.google.com/webstore/detail/bmoemkaigjgcgjjnpmdgkifndiidkeji
Gives a 404 error, searching for it doesn't work either.

**Comment by AnderssonPeter** [comment]
Is it dead? i sure hope not!

**Comment by noah978** [comment]
As a more temporary fix, do you know how to access the timestamps in netflix's viewing activity?

**Comment by Mosney** [comment]
So anyone know how to install now? Any crx file could be download?

**Comment by gsrafael01** [comment]
@noah978 

1. Visit the source code of https://www.netflix.com/Activate (view-source:https://www.netflix.com/Activate)
2. Search for "BUILD_IDENTIFIER":"[Value1]" and write down [Value1]
3. Search for "authUrl":"[Value2]" and write down [Value2]
4. Visit https://www.netflix.com/api/shakti/[Value1]/viewingactivity?authURL=[Value2]&pg=[Page], replacing [Value1] and [Value2] with the values you got from steps 2 and 3, and replacing [Page] with the page you want (starts at 0)

The dates are stored as an integer number, so to make it easier to get them, open the browser console (Ctrl + Shift + I) and paste this code:

```
json = JSON.parse(document.body.textContent.replace(/^.+?({)|(}).+?$/, `$1`));
for (const item of json.viewedItems) {
  console.log(`${item.seriesTitle}, ${item.seasonDescriptor}, ${item.episodeTitle}, ${new Date(item.date).toLocaleString()}`);
}
```

I'm currently porting the extension to Firefox and I hope to distribute it soon.

**Comment by noah978** [comment]
Thanks! That’s incredibly helpful, look forward to seeing the Firefox extension. 👍

**Comment by gsrafael01** [comment]
@noah978 An initial version is available here: https://github.com/gsrafael01/traktflix/blob/master/extension.zip You can load it by going to about:debugging#addons, clicking "Load Temporary Add-On..." and selection the .zip file. I tested syncing my history and scrobbling something, and it appears to be working fine. I intend to publish it in the Mozilla store after a few more tests so it's more convenient to install and update.

I believe Chrome users can also use this version without any issues. You just have to extract the files from the .zip file to a folder and load the folder through "Load unpacked" in the developer mode of Chrome's extensions page.

**Comment by gsrafael01** [comment]
For everyone interested: https://addons.mozilla.org/en-US/firefox/addon/traktflix/

**Comment by andyosier** [comment]
> I believe Chrome users can also use this version without any issues. You just have to extract the files from the .zip file to a folder and load the folder through "Load unpacked" in the developer mode of Chrome's extensions page.

That worked perfectly. Using it in Chrome right now.

**Comment by gsrafael01** [comment]
@andyosier The link was outdated, did you get v2.0.3? I've updated the link just now. The only annoying thing about using it on Chrome like this is that every time you open the browser you will get a message saying that using extensions in developer mode is dangerous and you will have to dismiss that message every single time. Unfortunately I can't pay Google's developer fee to distribute it in their store.

**Comment by andyosier** [comment]
I got v2.0.3 from the Mozilla website.

**Comment by vc4u** [comment]
Firefox addon worked like a charm. very helpful. Though, if I can ask one feature request, for if scrobble is enabled, it auto fullscreen the playing video. If at all it is possible :-)

**Comment by tegon** [comment]
Sorry everyone, I was away on vacations for a while and then I got sick so
I’m away from GitHub for a long time.
I only saw this now and I apologize for this.
Seems like Google removed it from the store because I was supposed to
update some privacy terms. When I get back home next week I’ll look into
that and as a last resource I can generate a file and upload it to the
website so that you can download directly.
Sorry again for all the trouble.

**Comment by BuSHari** [comment]
Feel better @tegon , maybe you can merge with @gsrafael01 fork?

**Comment by tegon** [comment]
Sure, I'm not sure what changed exactly though. 
@gsrafael01 What did you need to change in order to make it work with Firefox?

**Comment by Skardy** [comment]
![screenshot_39](https://user-images.githubusercontent.com/32639984/48969653-d8ef6000-f001-11e8-9940-f8ec4fdecba4.png)

@gsrafael01 
Everytime I open a movie/episode of a series, I get this error. This happens on 2 different pc's (both Firefox). Any idea how to solve this?

**Comment by gsrafael01** [comment]
@Skardy Can you turn on Rollbar in the options menu so I get some more info about the error?

**Comment by Skardy** [comment]
@gsrafael01 I just found out that the extension is not in my list on the top right corner. It is when I go to the Add-ons manager. It's the exact same on my other pc. It was never there to honest. Any idea?
![screenshot_40](https://user-images.githubusercontent.com/32639984/48971011-c3cffc80-f014-11e8-9fd4-bda7382020d0.png)

**Comment by gsrafael01** [comment]
@Skardy That's the default behavior, the extension only appears in the top right corner of the search bar when you are on a Netflix page (open any Netflix page and you'll see it).

**Comment by Skardy** [comment]
@gsrafael01 Oh wow, I feel so stupid. It works now, I didn't even notice that.
Thanks for your help and sorry for wasting your time. Awesome app though! Could use some improvement, but cool design!

**Comment by gsrafael01** [comment]
@Skardy If you have any suggestions for improvements, feel free to open an issue, I'd be happy to work on it.

**Comment by HakimD** [comment]
> @noah978
> 
> 1. Visit the source code of https://www.netflix.com/Activate (view-source:https://www.netflix.com/Activate)
> 2. Search for "BUILD_IDENTIFIER":"[Value1]" and write down [Value1]
> 3. Search for "authUrl":"[Value2]" and write down [Value2]
> 4. Visit [https://www.netflix.com/api/shakti/[Value1]/viewingactivity?authURL=[Value2]&pg=[Page]](https://www.netflix.com/api/shakti/%5BValue1%5D/viewingactivity?authURL=%5BValue2%5D&pg=%5BPage%5D), replacing [Value1] and [Value2] with the values you got from steps 2 and 3, and replacing [Page] with the page you want (starts at 0)
> 
> The dates are stored as an integer number, so to make it easier to get them, open the browser console (F12 or Ctrl + Shift + I) and paste this code:
> 
> ```
> json = JSON.parse(document.body.textContent.replace(/^.*?({)|(}).*?$/, `$1`));
> for (const item of json.viewedItems) {
>   console.log(`${item.seriesTitle}, ${item.seasonDescriptor}, ${item.episodeTitle}, ${new Date(item.date).toLocaleString()}`);
> }
> ```
> I'm currently porting the extension to Firefox and I hope to distribute it soon, in case anyone is interested in that.

Hi @gsrafael01 , @tegon 

I just discovered your work, its great!  Do you know why sometimes the api returns "undefined, undefined, undefined, 29/11/2018..."

Ty

**Comment by gsrafael01** [comment]
@HakimD Oh sorry, I forgot about movies. This should work:

```
json = JSON.parse(document.body.textContent.replace(/^.*?({)|(}).*?$/, `$1`));
for (const item of json.viewedItems) {
  if (item.seriesTitle) {
    console.log(`TV SHOW: ${item.seriesTitle}, ${item.seasonDescriptor}, ${item.episodeTitle}, ${new Date(item.date).toLocaleString()}`);
  } else {
    console.log(`MOVIE: ${item.title}, ${new Date(item.date).toLocaleString()}`);
  }
}
```

But there's no need to do that anymore, if you use the version I distributed for Firefox.

**Comment by HakimD** [comment]
@gsrafael01 It's ok. thanks. Is there any documentation on internet about how to use netflix's api?

**Comment by MrMamen** [comment]
I'm already a (minor) contributor to this repo, I may want to continue contributing. But has @tegon stopped maintaining this? I would gladly switch to @gsrafael01 but not if the end result is two diverging forks. I would like to see one unified traktflix project.

**Comment by gsrafael01** [comment]
@HakimD Unfortunately not. It's not really a public API. Someone started documenting it [here](https://github.com/HowardStark/shakti), but it's not a lot. So I've been mostly watching the Network tab of the browser to see how Netflix uses it.

@gsrafael01 Sure, made a PR. I can add `launchWebAuthFlow` back if you want, since you have a `chromiumapp.org` page.

**Comment by HakimD** [comment]
@gsrafael01 Ok thanks

**Comment by DiniOG** [comment]
I keep getting "Activate your device" on netflix when trying to connect the app.zip addon. I am stuck with logging in basically on chrome. I tried opening netflix on other devices for a code to popup but nothing at all.

**Comment by gsrafael01** [comment]
@DiniOG I just tested and got the same thing, but if I close the activate window and open the traktflix popup from the browser toolbar, it shows that I'm logged in. Does it not log you in at all?

**Comment by cobrabr** [comment]
@gsrafael01, @DiniOG -- that worked for me as well. Also, thanks a bunch for the improvements, @gsrafael01! :)

**Comment by FryGuy1981** [comment]
What is the status on the extension in the chrome store? Still working on getting it back?

**Comment by lonelyfairie** [comment]
I tried loading the extension in chrome as unpacked but I get an error saying unable to load manifest, is there any way around this?

**Comment by gsrafael01** [comment]
I don't know when @tegon will get the extension back in the Chrome store, and I don't want to overstep that distribution, since my main focus is Firefox, but I've published a temporary unlisted version of it: https://chrome.google.com/webstore/detail/traktflix/ehlckfimahifadnbecobagimllmbdmde I'll delete it as soon as the original extension is back in the store. I tested it very quickly and it seems to be working.

**Comment by MrMamen** [comment]
What is the current status of this repo? @tegon seems to be mostly away. But did @gsrafael01 get maintainer status? I have a few improvements I have been implementing on my traktNRK-fork, which I will be happy to contribute back to this project. But I will not bother doing so if my Pull Requests are ignored.

**Comment by thilux** [comment]
Any news on the status of getting trakflix back into Chrome Web Store?

**Comment by DiniOG** [comment]
Installing the extension by gsrafael01 works just fine. Just had issues with the manual extension we were having to install. Verified/activated instantly when signing into trakt.

**Comment by FryGuy1981** [comment]
The gsrafael01 extension works perfectly for me. Thank you.

**Comment by tegon** [comment]
I'm still having issues with Chrome Store privacy policy's 😞 
I've been unable to find time to work on this lately since I'm maintaining other open source projects now. But I'll try to work with @gsrafael01 to see whether we can publish a new version to the store.

I think for now it's better to use the unpublished version above.

**Comment by redxtech** [comment]
Just migrated to @gsrafael01's version. Looks like those were some good changes to implement.

What sort of issues are there with the new privacy policy? Is it just some stuff that you have to change in your policy or do you have to fundamentally change parts of the extension to comply?

**Comment by gsrafael01** [comment]
@redxtech Apparently they didn't say the exact reason why the extension was pulled. I believe that it could have been because of the use of Google Analytics and Rollbar without the consent of the user, but tegon said he submitted a version removing those features and it still was rejected. The last version he submitted was my version, which makes Google Analytics and Rollbar completely optional, so we'll see if they reject it this time.

**Comment by redxtech** [comment]
Ah ok sounds good. Yeah hopefully that would make it work with their policy. They really should tell you at least generally the part of their ToS/provacy policy that you're violating.

**Comment by raulcraveiro** [comment]
The @gsrafael01 Chrome version isn't working here, just the Firefox version. And I tried to upload the unpacked version on Microsoft Edge Chromium and it says that is missing a manifest file.

**Comment by raulcraveiro** [comment]
Oh, nevermind, when I changed the permissions on the extension, it worked. ♥
