### ISSUE TITLE
Can't find what I'm watching

### ISSUE THREAD

**Issue by Touratica** [tegon/traktflix#88]
I was trying to watch [Black Lightening 2x03 The Book of Consequences: Chapter Three: Master Lowry](https://www.netflix.com/watch/80997347), but the extension gave me this error where it couldn't find what I was watching. I'm using the extension version 1.0.8.3, Chrome 70.0.3538.77 and Windows 10.0.17134.376, my OS is in Portuguese (Portugal) and so is Netflix

**Comment by tegon** [comment]
Unfortunately, it only works with Netflix in English for now :/

**Comment by gsrafael01** [comment]
This should no longer be an issue in v2.0.8.
