### ISSUE TITLE
Fail to save option

### ISSUE THREAD

**Issue by Enterpr1se** [tegon/traktflix#93]
When I click "Save" in options, it said "Fail to save options", even I start firefox as administrater

**Comment by psxlover** [comment]
@gsrafael01 can you update the version in firefox addons page? I also run into this when trying to enable Rollbar and correction suggestions

**Comment by gsrafael01** [comment]
@psxlover I'll try to update it until tomorrow.

**Comment by gsrafael01** [comment]
Updated to v2.0.8.

**Comment by psxlover** [comment]
Thanks, works like a charm :)
