### ISSUE TITLE
TypeError: i.value.videos is undefined (Firefox)

### ISSUE THREAD

**Issue by MetalArend** [tegon/traktflix#97]
The following error shows up in the console in firefox with the latest version of the firefox plugin (2.0.8):

```
TypeError: i.value.videos is undefined history-sync.js:6:6143

    e moz-extension://924f3647-6799-3140-a0d8-e1d6ea279aad/js/history-sync.js:6
    map self-hosted:286 
    success moz-extension://924f3647-6799-3140-a0d8-e1d6ea279aad/js/history-sync.js:6
    onload moz-extension://924f3647-6799-3140-a0d8-e1d6ea279aad/js/history-sync.js:1 
```

It keeps hanging at "Loading page 1...".

I gave the plugin the new permissions. I completely reinstalled the plugin. I checked the Network tab, but the calls to Netflix seem fine.

**Comment by gsrafael01** [comment]
Are you using Firefox containers? If so, the extension doesn't work with that.

**Comment by MetalArend** [comment]
I'm not sure, but afaik I never activated any Firefox containers. Actually, I'm using a clean install of Firefox with only Netflix and Traktflix on it, only for this plugin, as the Chrome plugin is not officially available anymore.

**Comment by Sjohn21** [comment]
I have the same problem that the screen keeps hanging at loading page 1.
This is the problem for both Chrome as Firefox extension.
As this problem firstly occurred to me with the Chrome extension I was sure to update this to the latest one. (I had 2.0.4 running, the problem occurred). 
So I updated to 2.0.8 from the chrome store (direct link from Github). Which didn't work. So I though about trying Firefox extension. I didn't have Firefox installed yet on this machine so I did a full clean install of Firefox. Installed the Traktflix extension (2.0.8) and again it stays at "Loading page 1".
So i started looking in the console(s)

The console in Firefox show the following:
TypeError: i.value.videos is undefined[Meer info] history-sync.js:6:6143
	e moz-extension://1666bd13-ae29-4fb9-86d7-8f805e2ff4c7/js/history-sync.js:6
	map self-hosted:286
	success moz-extension://1666bd13-ae29-4fb9-86d7-8f805e2ff4c7/js/history-sync.js:6
	onload moz-extension://1666bd13-ae29-4fb9-86d7-8f805e2ff4c7/js/history-sync.js:1

The console in Chrome:
history-sync.js:6 Uncaught TypeError: Cannot read property '80190198' of undefined
    at history-sync.js:6
    at Array.map (<anonymous>)
    at XMLHttpRequest.success (history-sync.js:6)
    at XMLHttpRequest.i.onload (history-sync.js:1)

Hope this helps

**Comment by gsrafael01** [comment]
Weird that it didn't work for you with 2.0.4, as it was working fine for me a couple weeks ago, but I can reproduce it as well. I wonder if Netflix changed anything in their API.

**Comment by dizwod** [comment]
Same issue for me in firefox

**Comment by gsrafael01** [comment]
I can't pay Netflix at the moment, so I can't test this right now. Could anyone look at their network tab in the browser console when browsing around Netflix and filter any requests to `pathEvaluator` so we can see if Netflix changed something in their API?

**Comment by gsrafael01** [comment]
Nevermind, I found it on another Netflix project.

**Comment by gsrafael01** [comment]
Should be fixed in v2.0.9.

**Comment by Sjohn21** [comment]
Just to let you know. It indeed works again in both Chrome & Firefox in v2.0.9.

**Comment by MetalArend** [comment]
Yeah, it seems to be solved. Thanks for the fast response, and the awesome work!
